implementation with the help of hibernate ORM
Tolyaspit/AndersenCourse pull request #13
Opened 2024-09-29 12:54 UTC by Tolyaspit

Please check changes and approve it)

2024-09-30 05:13 UTC, Alexmansar requested changes
@Tolyaspit Hi, in general good job, few comments)

2024-09-30 05:13 UTC, Alexmansar commented on src/main/java/NewTicket.java
> +        this.creationDate = creationDate;
you can create creationDate in constructor)) 
 this.creationDate = LocalDate.now();

and not set it separately

2024-09-30 05:13 UTC, Alexmansar commented on src/main/java/NewTicketDAOImpl.java
> +            if (transaction != null) transaction.rollback();
```
if (transaction != null) {
     transaction.rollback();
}
```

2024-09-30 05:13 UTC, Alexmansar commented on src/main/java/NewUserDAOImpl.java
> +            if (transaction != null) transaction.rollback();
same

2024-09-30 05:13 UTC, Alexmansar commented on src/main/java/TicketService.java
> +        SessionFactory sessionFactory = new Configuration().configure("hibernate.cfg.xml").buildSessionFactory();
this could be in the separate class
and "hibernate.cfg.xml" could be constant

2024-09-30 05:13 UTC, Alexmansar commented on src/main/java/NewTicket.java
>  public class NewTicket {
why NewTicket? noy just Ticket?

2024-09-30 06:23 UTC, Alexmansar commented on src/main/java/NewTicket.java
>  public class NewTicket {
ok) In general for now its not a problem. But in real projects its not good idea))

2024-09-30 06:24 UTC, Tolyaspit commented on src/main/java/NewTicket.java
>  public class NewTicket {
Ok , got it)

2024-10-01 09:24 UTC, Alexmansar approved these changes
@Tolyaspit Could be merged

2024-10-01 18:13 UTC, merged