Spring.1
Tolyaspit/AndersenCourse pull request #15
Opened 2024-10-08 19:59 UTC by Tolyaspit

Please check changes and approve it

2024-10-09 17:41 UTC, Alexmansar requested changes
@Tolyaspit Hi)) in generl good job)) some small commets))

2024-10-09 17:41 UTC, Alexmansar commented on src/main/java/dao/NewTicketDAOImpl.java
> +    @Transactional
If you wnt add Transactional for all public methods, you can use it just on the class level

2024-10-09 17:41 UTC, Alexmansar commented on src/main/java/dao/NewUserDAOImpl.java
> +    @Transactional
same

2024-10-09 17:41 UTC, Alexmansar commented on src/main/java/model/NewUser.java
> +        return "model.NewUser{" +
do we need it ? I mean **model.**

2024-10-09 17:41 UTC, Alexmansar commented on src/main/java/service/NewTicketService.java
> +    private Resource ticketJson;
please use constructor injection) its more easy for testing) just advice

2024-10-09 17:41 UTC, Alexmansar commented on src/main/java/service/NewTicketService.java
> +    }
move to the separate class

2024-10-09 17:58 UTC, Tolyaspit commented on src/main/java/model/NewUser.java
> +        return "model.NewUser{" +
I'm also not sure how is it happening. I think it's because of cloning , and toString method changing in other classes also, even if I'm not working on that class, I guess during refactoring to the packages it happened

2024-10-09 17:58 UTC, Tolyaspit commented on src/main/java/dao/NewTicketDAOImpl.java
> +    @Transactional
Ok thanks:)

2024-10-10 06:28 UTC, Alexmansar approved these changes
@Tolyaspit Hi)) could be merged))

2024-10-10 08:03 UTC, merged