Spring v3 , Converting to Spring Boot
Tolyaspit/AndersenCourse pull request #16
Opened 2024-10-11 13:47 UTC by Tolyaspit

Please check changes and approve it)

2024-10-11 15:43 UTC, Alexmansar requested changes
@Tolyaspit Hi, in general good job)) small comments))

2024-10-11 15:43 UTC, Alexmansar commented on src/main/java/com/andersen/course/TicketsApp.java
> +@EntityScan(basePackages = {"com.andersen.course.model"})
could be in configuration class

2024-10-11 15:43 UTC, Alexmansar commented on src/main/java/com/andersen/course/config/Config.java
> +public class Config {
specify the name, like AppConfiguration

2024-10-12 12:59 UTC, Tolyaspit commented on src/main/java/com/andersen/course/config/Config.java
> +public class Config {
Like , leave the main method in the TicketApp and put the annotations to configuration class right?

2024-10-13 07:35 UTC, Alexmansar approved these changes
@Tolyaspit Hi)) olease, update code and merge it))

2024-10-13 07:35 UTC, Alexmansar commented on src/main/java/com/andersen/course/TicketsApp.java
> +public class TicketsApp {
please, return SpringBootApplication

2024-10-13 07:35 UTC, Alexmansar commented on src/main/java/com/andersen/course/TicketsApp.java
> +        SpringApplication.run(AppConfiguration.class, args);
TicketsApp. class

2024-10-13 07:35 UTC, Alexmansar commented on src/main/java/com/andersen/course/config/AppConfiguration.java
> +@SpringBootApplication
here remove))

2024-10-13 10:43 UTC, merged