New Commit
Tolyaspit/AndersenCourse pull request #7
Opened 2024-09-10 07:44 UTC by Tolyaspit

Please check changes and approve the request!

2024-09-10 07:49 UTC, Alexmansar requested changes
@Tolyaspit Hi, please check some comments

2024-09-10 07:49 UTC, Alexmansar commented on src/Abstract.java
> +//    }
uncommented it please

2024-09-10 07:49 UTC, Alexmansar commented on src/Abstract.java
> +public abstract class Abstract {
AbstractId for example or AbstractNumericId

2024-09-10 07:49 UTC, Alexmansar commented on src/Admin.java
> +    public void checkTicket(Ticket ticket) {
should return some boolean ( according to the name)

2024-09-10 07:49 UTC, Alexmansar commented on src/Abstract.java
> +    private int id;
make it protected)

2024-09-10 07:49 UTC, Alexmansar commented on src/Ticket.java
>      private String id;
we don't need it already (see parent class)

2024-09-10 07:49 UTC, Alexmansar commented on src/Ticket.java
>          }else {
move to the Abstract class

2024-09-10 07:49 UTC, Alexmansar commented on src/TicketService.java
> +        Admin admin = new Admin();
User admin = new Admin()

2024-09-10 07:49 UTC, Alexmansar commented on src/Admin.java
> +
add some logic

2024-09-10 08:49 UTC, Alexmansar requested changes
@Tolyaspit please, check small comments))

2024-09-10 08:49 UTC, Alexmansar commented on src/Ticket.java
>      }
you don't need it. You will use just parent methods

2024-09-10 08:49 UTC, Alexmansar commented on src/Ticket.java
> +    }
which super you use here?

2024-09-10 08:56 UTC, Tolyaspit commented on src/Ticket.java
> +    }
Oh , I used the default shortcut. Do I need to add the fields to compare for these override methods?

2024-09-11 07:25 UTC, Alexmansar commented on src/Ticket.java
> +        return time == ticket.time && isPromo == ticket.isPromo && Double.compare(maxAllowedBackpackWeight, ticket.maxAllowedBackpackWeight) == 0 && Double.compare(ticketPrice, ticket.ticketPrice) ==
please, start some code from new line))
```
return time == ticket.time 
   && isPromo == ticket.isPromo 
   && Double.compare(maxAllowedBackpackWeight, ticket.maxAllowedBackpackWeight) == 0 
   && Double.compare(ticketPrice, ticket.ticketPrice) == 0 
   && Objects.equals(concertHall, ticket.concertHall)
   && Objects.equals(eventCode, ticket.eventCode) 
   && timePeriod == ticket.timePeriod 
   && stadiumSector == ticket.stadiumSector;
```
good practice)

2024-09-11 07:25 UTC, Alexmansar approved these changes
@Tolyaspit Could be merged. Please just fix styling and merge))

2024-09-11 07:26 UTC, Tolyaspit commented on src/Ticket.java
> +        return time == ticket.time && isPromo == ticket.isPromo && Double.compare(maxAllowedBackpackWeight, ticket.maxAllowedBackpackWeight) == 0 && Double.compare(ticketPrice, ticket.ticketPrice) ==
Ok:)thanks

2024-09-11 07:29 UTC, merged